<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>51Talk Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      width: 100% !important;
      height: 100% !important;
      padding: 10px !important;
      margin: 0 !important;
      background-color: #e9ecef;
    }

    .content {
      background-color: #e9ecef;
      padding: 40px;
    }

    .logo {
      display: block;
      width: 30%;
      height: auto;
      border: 0;
    }

    .details {
      background-color: #ffffff;
      margin: 10px 0px 0px 0px;
      padding: 15px;
    }

    .ref-code-text {
      margin-top: 10px;
      margin-bottom: 0px;
      text-align: center;
    }

    .ref-code {
      color: #000;
      background-color: #ffe800;
      padding: 10px 20px;
      text-align: center;
      width: 35%;
      max-width: 45%;
      margin: 0px auto;
    }

    .footnote {
      padding: 10px;
      background-color: #e9ecef;
      font-size: 0.8em;
    }
  </style>
</head>

<body>
  <div class="content">
    <img src="{{ $data->logo }}" alt="Logo" class="logo">
    <div class="details">
      <h2>51Talk Health Declaration Form</h2>
      <p>
        {{-- {{ dd($data) }} --}}
        Hi {{ $data->data->fullname }}!
        <p>
          <p>
            @if ($data->data->passed)
              Thank you for answering the Health Declaration Form.<br>
              You may proceed to office on {{ date('Y-m-d', strtotime($data->data->date)) }}<br><br>
            @else
              Thank you for answering the Health Declaration Form.<br>
              Our HR team will reach out to you for further verification.<br><br>
            @endif
          </p>
          <hr>
          <p class="footnote">
            51Talk Philippines. This is autogenerated email. please do not reply.
          </p>
    </div>
  </div>
</body>

</html>