<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>51Talk Events</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body {
      width: 100% !important;
      height: 100% !important;
      padding: 10px !important;
      margin: 0 !important;
      background-color: #e9ecef;
    }

    .content {
      background-color: #e9ecef;
      padding: 40px;
    }

    .logo {
      display: block;
      width: 30%;
      height: auto;
      border: 0;
    }

    .details {
      background-color: #ffffff;
      margin: 10px 0px 0px 0px;
      padding: 15px;
    }

    .ref-code-text {
      margin-top: 10px;
      margin-bottom: 0px;
      text-align: center;
    }

    .ref-code {
      color: #000;
      background-color: #ffe800;
      padding: 10px 20px;
      text-align: center;
      width: 35%;
      max-width: 45%;
      margin: 0px auto;
    }

    .btn-reset {
      background-color: #ffe800;
      border: none;
      color: #00b4ee;
      padding: 20px;
      text-align: center;
      text-decoration: none;
      display: block;
      width: 280px;
      font-size: 1.2em;
      margin: auto;
      margin-bottom: 12px;
      font-weight: bolder;
      border-radius: 25%;
    }

    .footnote {
      padding: 10px;
      background-color: #e9ecef;
      font-size: 0.8em;
    }
  </style>
</head>

<body>
  <div class="content">
    <img src="{{ $data->app->logo }}" alt="Logo" class="logo">
    <div class="details">
      <h2>Reset your HDF password</h2>
      <p>
        {{-- {{ dd($data) }} --}}
        Hi {{ $data->user->fullname }}!
      </p>
      <p>
        We're sending you this email because you requested a password reset.
        Click this link to create a new password.
      </p>
      <a href="{{ $data->app->resetUrl }}" target="_blank" class="btn-reset">Reset Password</a>
      <hr>
      <p class="footnote">
        51Talk Philippines. This is autogenerated email. please do not reply.
      </p>
    </div>
  </div>
</body>

</html>